-- Generated by hypr2lua-web.

hl.config({
  general = {
    border_size = 2,
    gaps_in = 2,
    gaps_out = 4,
    col = {
      active_border = {
        colors = { "rgba(D9A441ff)", "rgba(7C9A4Dff)" },
        angle = 45,
      },
      inactive_border = {
        colors = { "rgba(5A564Ecc)", "rgba(3A3833cc)" },
        angle = 45,
      },
    },
  },
  animations = {
    enabled = true,
  },
  decoration = {
    rounding = 16,
    blur = {
      enabled = true,
      size = 4,
      passes = 3,
      contrast = 0.95,
      brightness = 0.9,
      vibrancy = 0.15,
      vibrancy_darkness = 0.25,
      noise = 0.015,
      ignore_opacity = true,
      new_optimizations = true,
    },
    active_opacity = 0.98,
    inactive_opacity = 0.92,
    fullscreen_opacity = 1.0,
  },
})

hl.curve("village", { type = "bezier", points = { { 0.22, 1 }, { 0.36, 1 } } })
hl.curve("borderEase", { type = "bezier", points = { { 0.22, 1 }, { 0.36, 1 } } })

hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 5,
  bezier = "village",
  style = "slide",
})
hl.animation({
  leaf = "windowsIn",
  enabled = true,
  speed = 5,
  bezier = "village",
  style = "slide",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 4,
  bezier = "village",
  style = "slide",
})
hl.animation({
  leaf = "windowsMove",
  enabled = true,
  speed = 5,
  bezier = "village",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 4,
  bezier = "village",
})
hl.animation({
  leaf = "fadeIn",
  enabled = true,
  speed = 4,
  bezier = "village",
})
hl.animation({
  leaf = "fadeOut",
  enabled = true,
  speed = 3,
  bezier = "village",
})
hl.animation({
  leaf = "layers",
  enabled = true,
  speed = 4,
  bezier = "village",
})
hl.animation({
  leaf = "layersIn",
  enabled = true,
  speed = 4,
  bezier = "village",
})
hl.animation({
  leaf = "layersOut",
  enabled = true,
  speed = 3,
  bezier = "village",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 6,
  bezier = "village",
  style = "slide",
})
hl.animation({
  leaf = "border",
  enabled = true,
  speed = 6,
  bezier = "borderEase",
})

hl.layer_rule({
  blur = true,
  match = {
    namespace = "walker",
  },
})
hl.layer_rule({
  ignore_alpha = 0,
  match = {
    namespace = "walker",
  },
})
hl.layer_rule({
  blur = true,
  match = {
    namespace = "waybar",
  },
})
hl.layer_rule({
  blur = true,
  match = {
    namespace = "notifications",
  },
})
hl.layer_rule({
  ignore_alpha = 0,
  match = {
    namespace = "notifications",
  },
})
hl.layer_rule({
  blur = true,
  match = {
    namespace = "vicinae",
  },
})
hl.layer_rule({
  blur = true,
  match = {
    namespace = "swayosd",
  },
})
hl.layer_rule({
  ignore_alpha = 0.1,
  match = {
    namespace = "waybar",
  },
})
hl.layer_rule({
  ignore_alpha = 0.1,
  match = {
    namespace = "vicinae",
  },
})
